### PR TITLE
Update llama2.mojo from MHA to GQA

### PR DESCRIPTION
**Pull request by magician-blue**
change from MHA to GQA

### CODE REVIEW

**Comment by magician-blue** [comment]
This did not bring about a significant inference speed improvement. Maybe there isn't a memory wall on CPU.

**Comment by magician-blue** [comment]
Oh, I know the reason why there isn't any speed up.
n_head == n_kv_heads for stories15M.bin,  stories110M.bin.
image

**Comment by tairov** [comment]
Hi @magician-blue , thans for sending PR. Could you please share some details , where is this GQA came from? 
As I understood istead of multi-head attention you're applying some other attention?
What is the benefits ? Probably on bigger models it can show some perfromance boosts?

**Comment by magician-blue** [comment]
The GQA I implement here is based on [run.py](https://github.com/karpathy/llama2.c/blob/master/run.c) from line 244.
GQA comes from this [paper](https://arxiv.org/pdf/2305.13245.pdf).

There are several kinds of attention. MHA(multihead attention which is implemented here), MQA(multiquery attention), GQA(group query attention, llama2). The GQA is a trade-off between MHA and MQA.
image

In MHA,
- $q = [q_1, q_2, ..., q_{nheads}]$ (n_heads * head_size)
- $k = [k_1, k_2, ..., k_{nheads}]$ (n_heads * head_size)
- $v = [v_1, v_2, ..., v_{nheads}]$ (n_heads * head_size)
- $o = [softmax(q_1k_1^T)v_1, softmax(q_1k_1^T)v_1,..., softmax(q_{nheads}k_{ nheads}^T)v_{nheads}]W_o$  (n_heads * head_size)

In MQA, in each layers all the queries share the same k,v.
- $q = [q_1, q_2, ..., q_{nheads}]$ (n_heads * head_size)
- $k = [k_1]$ (head_size)
- $v = [v_1]$ (head_size)
- $o = [softmax(q_1k_1^T)v_1, softmax(q_1k_1^T)v_1,..., softmax(q_{nheads}k_1^T)v_1,]W_o$  (n_heads * head_size)
This significantly save the memory use but do harms to the performance.

In GQA, in each layers all the queries share a group of k, v.
- $q = [q_1, q_2, ..., q_{nheads}]$ (n_heads * head_size)
- $k = [k_1, k_2, ..., k_{nkvheads}]$ (n_kv_heads * head_size)
- $v = [v_1, v_2, ..., v_{nkvheads}]$ (n_kv_heads * head_size)
- $o = [softmax(q_1k_1^T)v_1, softmax(q_1k_1^T)v_1,..., softmax(q_{nheads}k_{ nkvheads}^T)v_{nkvheads}]W_o$  (n_heads * head_size)
This means:
- From $q_1$ to $q_{nheads/nkvheads}$, I will use $k_1, v_1$.
- From $q_{1+nheads/nkvheads}$ to $q_{2 * nheads/nkvheads}$, I will use $k_2, v_2$.
- etc

Therefore, 
- If n_kv_heads = 1, GQA = MQA.
- If n_kv_heads = n_heads, GQA = MHA

In the case of story15M/42M/110M.bin, n_kv_heads = n_heads.
Thus, GQA is exactly the same as MHA.

**Comment by magician-blue** [comment]
There is something wrong in the code. Don't merge!

**Comment by tairov** [comment]
@magician-blue would you mind to share some thoughts how did you find out something was wrong ?

**Comment by magician-blue** [comment]
I have fix the bug and test it on stories260k.
It works fine.
image

**Comment by magician-blue** [comment]
I found there's little difference between our encoder/decoder and that of llama.c.
- Encoder: They sort the vocab to speed up the `str_lookup`.
- Decoder: There decoder can deal with `<0x01>,<0x0A>`, while our `print_str` can't.

**Comment by tic-top** [comment]
image
Now the tokenizer can output raw bytes.

```
Model name: intel(R) Core(TM) i7-10710U CPU @ 1.10GHz
CPU(s): 12
```

| Model on stories260k               | Speed (t/s) |
|--------------------|------------:|
| llama2.mojo        |       1770  |
| llama2.c           |       2000  |
| llama2.c (run fast)|       4200  |
| llama2.c (omp)     |       4700  |

**Comment by magician-blue** [comment]
> @magician-blue would you mind to share some thoughts how did you find out something was wrong ?

I just use the llam2a.c, view the intermediate variable and compare with llama2.mojo line by line.

**Comment by magician-blue** [comment]
> Now I see the tokenizer can output raw bytes. I test with `mojo llama2.mojo stories260K.bin -tk t260.bin -s 100 -n 256 -t 0 -i "Llama is an animal"` and `./run stories260K.bin -z t260.bin -i "Llama is an animal" -n 256 -t 0`
> 
> ```
> Model name: intel(R) Core(TM) i7-10710U CPU @ 1.10GHz
> CPU(s): 12
> ```
> 
> Model n=256 t= 0	260K	15M	110M
> llama2.c	2500-2800	51-52	7-8
> llama2.c (run fast)	5500-6000	118-119	18-20
> llama2.c (omp)	5000-6000	204-210	32-35
> llama2.mojo	2700-3000	190-205	31-32

I'm not sure why the inference speed of my implementation on stories260K is slower than llama2.c(runfast)

**Comment by tairov** [comment]
@magician-blue could you please add 260k tokenizer as well?

BTW, don't you know why `llama2.c` works fine on stories260k without tokenizer?

**Comment by magician-blue** [comment]
> @magician-blue could you please add 260k tokenizer as well?
> 
> BTW, don't you know why `llama2.c` works fine on stories260k without tokenizer?

Really? There is `Segmentation fault` if I didn't add the tokenizer.

**Comment by magician-blue** [comment]
@tairov I have added the t260.bin.

**Comment by tairov** [comment]
Shouldn't we add it to this repo ?

**Comment by tairov** [comment]
@magician-blue in your screen above ./run executing on stories260k without custom tokenizer option

**Comment by magician-blue** [comment]
I think we should add this tokenizer to the repo.

**Comment by tairov** [comment]
Overall I'm happy to merge. Just let's have this tokenizer in the repo , since ther could be questions where get that . 
Thanks

**Comment by tairov** [comment]
By some reason it's still failing for me:

```
mojo llama2.mojo stories260K.bin -tk t260.bin -n 256 -t 0.0
num hardware threads:  6
SIMD vector width:  16
checkpoint size:  67056
[320417:320417:20230918,234008.132002:ERROR file_io_posix.cc:144] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)
[320417:320417:20230918,234008.132146:ERROR file_io_posix.cc:144] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory (2)
Please submit a bug report to https://github.com/modularml/mojo/issues and include the crash backtrace along with all the relevant source codes.
Stack dump:
0.	Program arguments: mojo llama2.mojo stories260K.bin -tk t260.bin -n 256 -t 0.0
#0 0x000056013c1d3957 (/home/user/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x5bb957)
#1 0x000056013c1d152e (/home/user/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x5b952e)
#2 0x000056013c1d402f (/home/user/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x5bc02f)
#3 0x00007fb05b56f420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
#4 0x00007fafe4003840
[1]    320415 segmentation fault (core dumped)  mojo llama2.mojo stories260K.bin -tk t260.bin -n 256 -t 0.0
```

**Comment by tairov** [comment]
tried this options as well:
```
mojo llama2.mojo stories260K.bin -tk t260.bin -s 100 -n 256 -t 0 -i "Llama is an animal"
```

**Comment by tairov** [comment]
I see difference in checkpoint sizes on your example and my. 
UPD.. My bad, seems I put wrong file as mode.

**Comment by tairov** [comment]
merged. Thank you!

**Pull request merged**
