### PR TITLE
Simple Gradio UI + Dockerfile

### PR DESCRIPTION
**Pull request by radames**
Hi here a PR adding instructions on how to run a Mojo with a Dockerfile, following their dockerfile example
Also added a simple Gradio web UI to visualize the stdout
You can see the live demo here 
https://huggingface.co/spaces/radames/Gradio-llama2.mojo
ps: If you'd like I could add the HuggingFace link to your Readme?

### CODE REVIEW

**Comment by tairov** [comment]
thanks for PR, looks cool 
HW specs seems powerful, don't you know why on HF it shows 220 tok/s ? 
```
num hardware threads:  16  SIMD vector width:  32
```

**Comment by radames** [comment]
not sure, should it be faster?

**Comment by tairov** [comment]
Probably it also depends on CPU Mhz.. On 6 core cpu with SIMD vector width = 16, it's showing 385 tok/s

**Comment by tairov** [comment]
thanks for docker example, some folks were asking for it already 👍

**Pull request merged**
