### PR TITLE
Stop generating when EOS BOS appear

### PR DESCRIPTION
**Pull request by tic-top**
Stop generating when EOS BOS appear.

### CODE REVIEW

**Comment by tic-top** [comment]
Instead of calculating q,v and store q,v into q_cache, v_cache, we can do calculation directly on q_cache, v_cache.
This speed up the inference about 10%.

**Comment by tairov** [comment]
Hi @tic-top , thanks for PR, I'll take a look. 
The improvements sounds cool, did you benchmarked this ?

**Comment by tairov** [comment]
Found an issue with tok/s calculation.
We should use `pos - 1` instead of `steps - 1` 
```
print("\nachieved tok/s: ", (pos - 1) / (end - start) * 1000)
```

After this fix, it seems that current PR doesn't show any significant improvement. Maybe I got few % average generation speed increase. 

I would keep the original notation without changes. `Q,K,V` seem to be important parts of `transformer` algo

**Comment by tic-top** [comment]
Yes, you're right. The improvement is caused by  tok/s calculation.
I have made a little change which can't make significant improvement but save a little memory.
I use a tmp matrix pointing to k_cache and v_cache and do calculation on the cache.
This modification almost keep the original notation unchanged.

**Pull request merged**
